### ISSUE TITLE
收藏功能好像完全紊乱了

### ISSUE THREAD

**Issue by zhanglintc** [zhanglintc/Mmrz-Sync#27]
@smilebin818 在我完成 #23 后, 收藏功能完全紊乱了. 可能是影响到了你的既存处理.

当然也不确定是不是我感觉错了.

反正请尽快解析一下. 如果是bug就尽快讨论解决方案.

**Comment by smilebin818** [comment]
bug fix :+1: 789c6449ffd4fb3adae27a5ca323e45094aebd70

**Comment by zhanglintc** [comment]
:+1:

**Comment by zhanglintc** [comment]
111

**Comment by zhanglintc** [comment]
刷
