### ISSUE TITLE
[Easy]图标显示的时候不再发生闪烁

### ISSUE THREAD

**Issue by zhanglintc** [zhanglintc/Mmrz-Sync#3]
考虑CSS调用的时候的写法. 不要每次都发生网络请求.

**Comment by zhanglintc** [comment]
@smilebin818 这个什么时候搞?

**Comment by zhanglintc** [comment]
参考: [Javascript图片预加载详解](http://m.blog.csdn.net/article/details?id=46227115)

**Comment by smilebin818** [comment]
OK！！8360e869d8ca2e18f50627cf2ca3ab90dfc6c122

**Comment by zhanglintc** [comment]
我觉得这个东西并没有修好

**Comment by zhanglintc** [comment]
这回应该是真の解决了, 版本号区间:
12f2afcd6c4af6870478ee5d815bcf303bb80c75 => 209dbe120c9d0fbf2eebdfd49130eb713296c835

**Comment by zhanglintc** [comment]
不行不行, 再开, 再换方法尝试

**Comment by zhanglintc** [comment]
@smilebin818 感觉 `(new Image()).src = "/img/speak_manual.png";` 这样的方法好像是成功了
