### ISSUE TITLE
同样wordID的单词可以被重复收藏?

### ISSUE THREAD

**Issue by zhanglintc** [zhanglintc/Mmrz-Sync#30]
参照下图, 115和116是同一个单词:
![image](https://cloud.githubusercontent.com/assets/6189111/24025347/bd9ee1d4-0af4-11e7-8a07-76fef431bd11.png)

而且可以直接查看.db文件, 115和116的wordID都是一样的, 并不是长得一样的两个不同单词:
![image](https://cloud.githubusercontent.com/assets/6189111/24025208/15880cc8-0af4-11e7-8cac-88d489253193.png)

**Comment by smilebin818** [comment]
OK : bef2e5e7dfc0fa7703f0e265c1e9a8da4fdcd213
